playlists:
  daytime: "2dtGpG8ColpwGLjAIh3h2y"
  evening: "2M199fyV4J4gT1MfusqJxJ"
  folk: "5VcKxY0sYxapLRW1DSUvQr"
  party: "4kn274GiOqPmh6pgwG1nPZ"
  waltz: "5AsuhvTJGEZSNfLi89M3pF"
  rave: "5MwjTAKFh33Qhx8t5JZ2h2"

lastfm_tags:
  - "ukrainian"
  - "ukrainian pop"
  - "ukrainian folk"
  - "ukrainian rock"
  - "ukrainian electronic"
  - "ukrainian hip-hop"
